---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-secretless
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-secretless
  labels:
    app: cityapp-secretless
spec:
  ports:
  - port: 80
    nodePort: 30082
    name: http
  selector:
    app: cityapp-secretless
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-secretless
  name: cityapp-secretless
spec:
  selector:
    matchLabels:
      app: cityapp-secretless
  replicas: 1
  template:
    metadata:
      labels:
        app: cityapp-secretless
    spec:
      serviceAccountName: cityapp-secretless
      containers:
      - image: localhost/cityapp:1.0
        imagePullPolicy: IfNotPresent
        name: cityapp
        env:
        - name: DBAddress
          value: "127.0.0.1"
        - name: DBPort
          value: "3306"
        - name: DBName
          value: "world"
        - name: DBPassword
          value: ""
        - name: DBUsername
          value: ""
        ports:
          - containerPort: 80
      - image: docker.io/cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        name: authenticator
        args: ["-f", "/etc/secretless/cityapp-secretless-cm.yaml"]
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: JWT_TOKEN_PATH
            value: /var/run/secrets/tokens/jwt
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: conjur-connect-apps
        volumeMounts:
        - mountPath: /etc/secretless
          name: config
          readOnly: true
        - mountPath: /var/run/secrets/tokens
          name: jwt-token
      volumes:
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: vxlab
        - name: config
          configMap:
            name: cityapp-secretless-cm
