apiVersion: v1
kind: Service
metadata:
  name: hardcode
  namespace: cityapp
spec:
  clusterIP: None
  selector:
    app: hardcode
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hardcode
  namespace: cityapp
spec:
  ingressClassName: nginx
  rules:
  - host: hardcode.cityapp.vx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hardcode
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardcode
  namespace: cityapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardcode
  template:
    metadata:
      labels:
        app: hardcode
    spec:
      containers:
      - name: cityapp
        image: docker.io/joetanx/cityapp:php
        imagePullPolicy: IfNotPresent
        env:
        - name: DBADDR
          value: mysql.vx
        - name: DBPASS
          value: Cyberark1
        - name: DBUSER
          value: cityapp
