---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-hardcode
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-hardcode
  labels:
    app: cityapp-hardcode
spec:
  ports:
  - port: 80
    nodePort: 30080
    name: http
  selector:
    app: cityapp-hardcode
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-hardcode
  name: cityapp-hardcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-hardcode
  template:
    metadata:
      labels:
        app: cityapp-hardcode
    spec:
      serviceAccountName: cityapp-hardcode
      containers:
      - image: localhost/cityapp:1.0
        imagePullPolicy: IfNotPresent
        name: cityapp
        env:
          - name: DBAddress
            value: "mysql.vx"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "cityapp"
          - name: DBPassword
            value: "Cyberark1"
        ports:
        - containerPort: 80
          name: http
