---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hardcode
---
apiVersion: v1
kind: Service
metadata:
  name: hardcode
  labels:
    app: hardcode
spec:
  ports:
  - port: 8080
    nodePort: 30080
    name: http
  selector:
    app: hardcode
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardcode
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hardcode
  template:
    metadata:
      labels:
        deployment: hardcode
    spec:
      serviceAccountName: hardcode
      containers:
      - name: cityapp
        image: docker.io/joetanx/cityapp:php
        imagePullPolicy: IfNotPresent
        env:
        - name: DBADDR
          value: mysql.vx
        - name: DBPASS
          value: Cyberark1
        - name: DBUSER
          value: cityapp