---
apiVersion: v1
kind: Namespace
metadata:
  name: conjur
---
apiVersion: v1
kind: Namespace
metadata:
  name: cityapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: follower
  namespace: conjur
